#!/usr/bin/env python3

from argparse import ArgumentParser as AP
parser = AP()
parser.add_argument( 'list', nargs='+' )
parser.add_argument( '--ret' )
args=parser.parse_args()
numlist=list(map(eval,args.list))
print(f'# {numlist}')
a=0
for ii in numlist: a += ii
print( f'# result: {a}' )
if args.ret:
    print( f'export {args.ret}_RESULT="{a}"' )
    
