#!/bin/bash
main () {
    export NEWF_CLIENT=
    export NEWF_PROXY=
    export NEWF_ZERO=$1 ; shift
    while [ "$1" = "}set" ]; do export NEWF_$2=$3; shift 3; done
    export NEWF_MAIN=${NEWF_CLIENT:-$NEWF_ZERO}
    . ${NEWF_MAIN}.init "$@"
    [ x$1 = x}die ] && return $2
    ${NEWF_MAIN}.main "$@"
}
main $0 "$@"
export NEWF_EXITERR=$?
set | grep ^NEWF_EXIT
x () { return $1; }
[ -f $0 ] && exit $NEWF_EXITERR
x $NEWF_EXITERR
