#!/usr/bin/env python3
import os
from pathlib import Path
from textwrap import indent

def lfilter(*a,**b): return list(filter(*a,**(b)))
def isfile(path): return path.is_file()
def first(*paths): return (lfilter(isfile,paths)+[None])[0]
def main_4_beach(b): return first( b/'.beach'/'__main__' , b/'__poet__'/'__main__')
def is_beach(path):  return bool(main_4_beach(path))
def root(beach): return is_beach(beach) and root(beach.parent) or beach

HERE = Path(os.environ.get('EZ_here'))
NAME=HERE.relative_to(root(HERE).parent)
SUBS =list(HERE.glob('[a-z]*'))
SPACE =' '
PAD =SPACE*8

def help4cmd(path, long=False):
    if long: help=path/'.opts/long-help'
    else:    help=path/'.opts/short-help'
    if help.is_file(): return help.read_text().strip()
    else: return 'undocumented'

def main():
    def print_subcommands():
        print(f"SUBCOMMANDS:" )
        width = max(len(sub.name) for sub in SUBS)
        name = lambda sub : sub.name.ljust(width)
        doc = lambda sub : help4cmd(sub)
        for sub in SUBS:
            print( f"{PAD}{name(sub)} - {doc(sub)}" )

    if SUBS: print(f"USAGE:\n{PAD}{NAME} SUBCOMMAND" )
    else:    print(f"USAGE:\n{PAD}{NAME}" )

    if SUBS: print_subcommands()
    else:    pass

    print("LONGHELP:")
    print(indent( help4cmd(HERE,long=True),PAD))






if __name__ == "__main__":
    main()

