#!/bin/bash

__dispatch__ () {

    # Z = the client's full pathname ($0)
    export Z=$1 ; shift
    echo "[__dispatch__] assert: [$(basename $Z)] is [__main__]"

    # R = the client's root directory
    export  R=$(dirname $Z)     # D - root directory of client

    # O = the client's options directory
    export O=${R}/__opts__

    # handle options -h and --help
    [ $1. = -h.     ] && ${O}/__help__ $Z $* && return
    [ $1. = --help. ] && ${O}/__help__ $Z $* && return



    # process options
    while [ -f $O/o$1 ]; do . $O/o$1 $Z $*; shift; done

    # C = the client's subcommand
    C=$1; shift

    S1=$R/$C
    S2=$R/$C/__main__

    if   [ "$C" = "" ]; then fn__null__ ${Z}
    elif [ -f ${S1}  ]; then ${S1}      ${*}
    elif [ -f ${S2}  ]; then ${S2}      ${*}
    elif [ true      ]; then fn__main__ ${C} ${*}
    fi
}




fn__null__() { echo fn__null__ [$*]; }
fn__main__() { echo fn__main__ [$*]; }

__dispatch__ $0 $*
