#!/bin/bash
export BLhere=$(dirname $BLthis)
export BLname=$(basename $BLproxy)
export BLPOET_ROOT=$(dirname $__BLESSED_CLIENT__)
POET_ROOT=$BLhere
[ -f $BLthis.$1 ] && {
    $BLdot $BLthis.$*
} || {
    $BLthis.usage $*
}

