#!/bin/bash
export_ () { export $1="$2"; }
export_ BLhere          $(dirname $BLthis)
export_ BLname          $(basename $BLproxy)
export_ BLPOET_ROOT     $(dirname $__BLESSED_CLIENT__)
export_ BEACH_PROXY     $BLproxy
export_ BEACH_EASYCALL   "$BLproxy easy-invoke"
export_ BEACH_EASYSOURCE ". $BLproxy easy-invoke"
export_ BEACH__USAGE    $BLhere/dunders/__usage__
export_ BEACH__PARSE    $BLhere/dunders/__parse__
export_ BEACH__HANDLE   $BLhere/dunders/__handle__
export_ BEACH__EVAL     $BLhere/dunders/__eval__
export_ BEACH__DEFAULTS $BLhere/defaults
POET_ROOT=$BLhere
[ -f $BLthis.$1 ] && {
    $BLdot $BLthis.$*
} || {
    $BLthis.usage $*
}

